"""
Base class for trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, Any, Optional
from datetime import datetime

import pandas as pd
import numpy as np


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    direction: str  # "buy", "sell", "hold"
    strength: float  # 0.0 to 1.0
    price: Decimal
    timestamp: datetime
    timeframe: str
    strategy: str
    metadata: Dict[str, Any]
    
    def __post_init__(self):
        """Validate signal strength."""
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError("Signal strength must be between 0.0 and 1.0")


class BaseStrategy(ABC):
    """Base class for all trading strategies."""
    
    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None):
        """Initialize strategy.
        
        Args:
            name: Strategy identifier
            params: Strategy-specific parameters
        """
        self.name = name
        self.params = params or {}
        self.version = "1.0.0"
    
    @abstractmethod
    def generate_signal(self, data: pd.DataFrame) -> Optional[Signal]:
        """Generate trading signal from market data.
        
        Args:
            data: DataFrame with OHLCV data
            
        Returns:
            Signal object or None if no signal
        """
        pass
    
    def validate_data(self, data: pd.DataFrame) -> bool:
        """Validate that data has required columns.
        
        Args:
            data: DataFrame to validate
            
        Returns:
            True if valid, False otherwise
        """
        required_columns = ["open", "high", "low", "close", "volume"]
        return all(col in data.columns for col in required_columns)
    
    def calculate_indicators(self, data: pd.DataFrame) -> pd.DataFrame:
        """Calculate technical indicators.
        
        Args:
            data: OHLCV DataFrame
            
        Returns:
            DataFrame with added indicator columns
        """
        # To be overridden by subclasses
        return data
    
    def get_metadata(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Get additional metadata for signal.
        
        Args:
            data: Market data
            
        Returns:
            Dictionary of metadata
        """
        return {
            "strategy": self.name,
            "version": self.version,
            "data_points": len(data),
        }
